### ISSUE TITLE
License

### ISSUE THREAD

**Issue by julianstirling** [ZhuangLab/3D-printing#1]
@HazenBabcock

What licence are these files released under? We would love to be able to re use some of the functions in a project that is CERN Open Hardware Licensed.

Thank you for making this open!

**Comment by HazenBabcock** [comment]
They didn't have one, but now it is CERN OHL 1.2. Hopefully I did this correctly.

**Comment by julianstirling** [comment]
Thank you!

Looks great. As long as it is clear it does not matter how it is done :+1: 
One convention that some bots look for is a file called a plain text file of the license text called "LICENSE", but what you have done is equally clear.
